
var H5 = new H5();
H5.addPage('page1',{
  text:''
})
.addComponent('base',{
    name:'caption',
    type:'base',
    text:'',
    width:520,
    height:115,
    center:true,
    //html标签模板
    tpls:['.caption'],
    css:{
     background:'',
     top:230
   }
})
.addComponent('base',{
    name:'next_page',
    type:'base',
    html:'<i class="fa fa-chevron-down" aria-hidden="true"></i>',
    width:50,
    height:50,
    center:true,
    css:{
     top:890
   }
})
.addComponent('base',{
    name:'computer',
    type:'base',
    text:'',
    width:600,
    height:353,
    center:true,
    //html标签模板
    tpls:['.computer'],
    css:{
     backgroundImage:'url(./images/device-main.jpg)',
     backgroundSize:'100% auto',
     backgroundPosition:'50% top',
     top:365
   }
})
.addPage('page2',{
  text:''
})
.addComponent('base',{
    name:'blog',
    type:'base',
    text:'',
    width:1200,
    height:'100%',
    center:true,
    //html标签模板
    tpls:['.lk-blog-item,.lk-blog-about'],
    css:{
        top:157
    }
})
.addPage('page3',{
  text:'测试第三屏'
})
.addPage('page4',{
  text:'测试第四屏'
})
.addPage('page5',{
  text:'测试第五屏'
})
.loader(['images/logo.png'],2);


$('.lk-right-controller').click(function(){
    $(this).toggleClass('active');
    if($(this).hasClass('fa-align-justify')){
       $(this).removeClass('fa-align-justify').addClass('fa-close');
    }else{
        $(this).removeClass('fa-close').addClass('fa-align-justify');
    }
    $('.grid-music-container').toggleClass('active');
    $('.navbar,.mask').toggleClass('active');
});
